spring:
  datasource:
    # serverTimezone 设置时区 北京时间东八区GMT%2B8
    # useSSL 与服务器进行通信时使用SSL（真／假），默认值为“假”。
    url: jdbc:mysql://localhost:3306/crayonblog?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yaojikai2
  # redis 配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0