spring:
  datasource:
    # serverTimezone 设置时区 北京时间东八区GMT%2B8
    # useSSL 与服务器进行通信时使用SSL（真／假），默认值为“假”。
    url: jdbc:mysql://localhost:3306/crayon_blog?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yaojikai2
  data:
    redis:
      port: 6379
      host: 127.0.0.1

mybatis:
  configuration:
    # 驼峰下划线命名自动转换
    map-underscore-to-camel-case: true
